Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/alt/python312/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:1176][1325816] Child process with pid: 1325868 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:1176][1325816] Child process with pid: 1326043 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:1176][1325816] Child process with pid: 1326083 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:1176][1325816] Child process with pid: 1326121 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:1176][1325816] Child process with pid: 1328090 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/passenger_wsgi.py", line 15, in <module>
    from myproject.wsgi import application
  File "/home/xdnmancr/sandbox.wemakesoftwares.com/crew_wemakesoftwares/myproject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xdnmancr/virtualenv/sandbox.wemakesoftwares.com/crew_wemakesoftwares/3.12/lib/python3.12/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:1176][1325816] Child process with pid: 1328479 was killed by signal: 15, core dumped: no
Not Found: /staticfiles/css/bootstrap.min.css
Not Found: /staticfiles/css/fontawesome-all.min.css
Not Found: /staticfiles/images/graphic5.svg
Not Found: /staticfiles/css/iofrm-theme9.css
Not Found: /staticfiles/css/iofrm-style.css
Not Found: /staticfiles/images/logo-light.svg
Not Found: /staticfiles/js/jquery.min.js
Not Found: /staticfiles/js/bootstrap.bundle.min.js
Not Found: /staticfiles/js/registration_wizard_func.js
Not Found: /staticfiles/js/main.js
Not Found: /staticfiles/js/popper.min.js
[UID:1176][1336760] Child process with pid: 1336784 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1336795 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1336796 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1336797 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1336798 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1336794 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1339643 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1339692 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1339698 was killed by signal: 15, core dumped: no
[UID:1176][1336760] Child process with pid: 1339699 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341360 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341369 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341370 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341371 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341372 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341373 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341375 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341450 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341447 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341459 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341448 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341449 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341442 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341467 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341469 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341465 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341466 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341468 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341470 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341464 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341485 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341494 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341496 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341495 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341492 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341559 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341501 was killed by signal: 15, core dumped: no
[UID:1176][1341347] Child process with pid: 1341722 was killed by signal: 15, core dumped: no
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js//ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
Not Found: /ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js//ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js//ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
Not Found: /ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js//ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
